DROP TABLE AAA_TRSF_CLIENTS;
DROP TABLE AAA_TRSF_CLIENTS_IDS;

CREATE TABLE AAA_TRSF_CLIENTS
( FULLNAME VARCHAR2(150 char)
, BIRTHDAY VARCHAR2(30 char)
, DOC_SERIES VARCHAR2(10 char)
, DOC_NUMBER VARCHAR2(10 char)
);


CREATE TABLE AAA_TRSF_CLIENTS_IDS
( LAST_NAME VARCHAR2(50 char)
, FIRST_NAME VARCHAR2(50 char)
, MID_NAME VARCHAR2(50 char)
, BIRTHDAY DATE
, DOC_SERIES VARCHAR2(10 char)
, DOC_NUMBER VARCHAR2(10 char)
, PARTY_ID VARCHAR2(15 char)
, CON_BU_ID VARCHAR2(15 char)
, POSTN_CON_ID VARCHAR2(15 char)
, PS_CREDEN_ID VARCHAR2(15 char)
, CONTACT_MDMID VARCHAR2(15 char)
, DUL_MDMID VARCHAR2(15 char)
);


quit;