UNRECOVERABLE 
LOAD DATA
CHARACTERSET CL8MSWIN1251
APPEND 
INTO TABLE AAA_TRSF_CLIENTS TRUNCATE
FIELDS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
 FULLNAME CHAR(150),
 BIRTHDAY CHAR(30),
 DOC_SERIES CHAR(10),
 DOC_NUMBER CHAR(10),
 EXPER_MDM_ID CHAR(30),
 EXPER_STAB CHAR(30)
 )