--Запрос находит все просроченные активности у сотрудника
SELECT
      T22.CONFLICT_ID,
      T22.DB_LAST_UPD_SRC,
      T22.DB_LAST_UPD,
      T22.LAST_UPD,
      T22.CREATED,
      T22.LAST_UPD_BY,
      T22.CREATED_BY,
      T22.MODIFICATION_NUM,
      T22.ROW_ID,
      T22.CREATED_BY,
      T22.ACTIVITY_UID,
      T22.ALARM_FLAG,
      T4.APP_FLG,
      T4.APP_ID,
      T20.APP_NUM,
      T22.APPT_ALARM_TM_MIN,
      T22.COMMENTS_LONG,
      T22.COMMENTS,
      T14.WORK_PH_NUM,
      T22.CREATOR_LOGIN,
      T22.NAME,
      T22.CAL_TYPE_CD,
      T22.TODO_ACTL_END_DT,
      T22.DONE_FLG,
      T22.APPT_START_DT,
      T22.TODO_DUE_DT,
      T4.EMAIL,
      T22.APPT_END_DT,
      T22.PAR_EVT_ID,
      T22.TARGET_PER_ADDR_ID,
      T4.PHONE,
      T22.TODO_PLAN_START_DT,
      T22.TODO_PLAN_END_DT,
      T9.NAME,
      T22.OWNER_POSTN_ID,
      T14.FST_NAME,
      T22.TARGET_PER_ID,
      T14.LAST_NAME,
      T14.MID_NAME,
      T22.PR_OPTY_ID,
      T22.OWNER_LOGIN,
      T11.BU_ID,
      T22.OWNER_PER_ID,
      T22.EVT_PRIORITY_CD,
      T22.APPT_REPT_FLG,
      T22.APPT_REPT_END_DT,
      T22.APPT_REPT_TYPE,
      T4.X_BALANCE_RUR,
      T16.FST_NAME,
      T16.LAST_NAME,
      T4.SBRF_CAMP_CON_ID,
      T14.BIRTH_DT,
      T8.LOGIN,
      T10.FST_NAME,
      T10.LAST_NAME,
      T10.MID_NAME,
      T10.PR_HELD_POSTN_ID,
      T4.X_CUR_AMNT,
      T14.PR_EMAIL_ADDR_ID,
      T14.PR_ALT_PH_NUM_ID,
      T14.CUST_VALUE_CD,
      T4.SBRF_DTL_RSN,
      T22.X_GFL_PRODUCT_NUM,
      T22.X_TODO_PLAN_TMP_DT,
      T14.CUST_VALUE_CD,
      T22.X_PR_OWNER_DIV_ID,
      T4.X_REQUIRED_AMNT,
      T4.X_SBRF_SELLING_COUNT,
      T4.SBRF_STATUS_DETAIL,
      T4.SBRF_SUBJECT,
      T4.SBRF_SUBJECT_DETAIL,
      T6.NAME,
      T4.X_SBRF_PRMR_PLAN_DATE,
      T4.X_SBRF_PRMR_PLAN_END_TIME,
      T4.X_SBRF_PRMR_PLAN_START_TIME,
      T22.TODO_CD,
      T5.X_BIS_TYPE,
      T4.X_SBRF_PRMR_SMS_REMINDER,
      T22.TODO_ACTL_START_DT,
      T22.EVT_STAT_CD,
      T22.X_SUB_TYPE_CD,
      T22.TEMPLATE_FLG,
      T22.TODO_CD,
      T4.SBRF_TYPE_LIC,
      T22.SUBTYPE_CD,
      T2.FST_NAME,
      T15.ROW_ID,
      T2.LAST_NAME,
      T2.MID_NAME,
      T3.X_SBRF_OPTY_NUMBER,
      T20.ROW_ID,
      T20.ROW_ID,
      T20.MODIFICATION_NUM,
      T20.DB_LAST_UPD,
      T8.ROW_ID,
      T8.ROW_ID,
      T8.MODIFICATION_NUM,
      T8.DB_LAST_UPD,
      T10.ROW_ID,
      T10.ROW_ID,
     T10.MODIFICATION_NUM,
      T10.DB_LAST_UPD,
      T5.ROW_ID,
      T5.ROW_ID,
      T5.MODIFICATION_NUM,
      T5.DB_LAST_UPD,
      T11.ROW_ID,
      T11.PAR_ROW_ID,
      T11.MODIFICATION_NUM,
      T11.DB_LAST_UPD,
      T6.ROW_ID,
      T6.ROW_ID,
      T6.MODIFICATION_NUM,
      T6.DB_LAST_UPD,
      T14.ROW_ID,
      T14.PAR_ROW_ID,
      T14.MODIFICATION_NUM,
      T14.DB_LAST_UPD,
      T16.ROW_ID,
      T16.PAR_ROW_ID,
      T16.MODIFICATION_NUM,
      T16.DB_LAST_UPD,
       T9.ROW_ID,
      T9.PAR_ROW_ID,
      T9.MODIFICATION_NUM,
      T9.DB_LAST_UPD,
      T4.ROW_ID,
      T4.PAR_ROW_ID,
      T4.MODIFICATION_NUM,
      T4.CREATED_BY,
      T4.LAST_UPD_BY,
      T4.CREATED,
      T4.LAST_UPD,
      T4.DB_LAST_UPD,
      T4.DB_LAST_UPD_SRC,
      T4.CONFLICT_ID,
      T4.PAR_ROW_ID,
      T12.ROW_ID,
      T12.CON_ID,
     T12.ACTIVITY_ID,
      T12.DB_LAST_UPD,
      T15.ROW_ID,
      T15.ROW_ID,
      T15.DB_LAST_UPD,
      T2.ROW_ID,
      T2.PAR_ROW_ID


   FROM
       SIEBEL.S_CONTACT T2,
       SIEBEL.S_OPTY T3,
       SIEBEL.S_EVT_ACT_X T4,
       SIEBEL.S_POSTN T5,
       SIEBEL.S_ORG_EXT T6,
       SIEBEL.S_USER T8,
       SIEBEL.S_POSTN T9,
       SIEBEL.S_CONTACT T10,
       SIEBEL.S_CONTACT T11,
       SIEBEL.S_ACT_CONTACT T12,
       SIEBEL.S_CONTACT T14,
       SIEBEL.S_PARTY T15,
       SIEBEL.S_CONTACT T16,
       SIEBEL.CX_APPEAL T20,
       SIEBEL.S_EVT_ACT T22
   WHERE
      T4.APP_ID = T20.ROW_ID (+) AND
      T22.CREATED_BY = T8.ROW_ID (+) AND
      T22.CREATED_BY = T10.ROW_ID (+) AND
      T10.PR_HELD_POSTN_ID = T5.ROW_ID (+) AND
      T22.OWNER_PER_ID = T11.PAR_ROW_ID (+) AND
      T22.X_PR_OWNER_DIV_ID = T6.ROW_ID (+) AND
      T22.TARGET_PER_ID = T14.PAR_ROW_ID (+) AND
      T4.SBRF_CAMP_CON_ID = T16.PAR_ROW_ID (+) AND
      T22.OWNER_POSTN_ID = T9.PAR_ROW_ID (+) AND
      T22.ROW_ID = T4.PAR_ROW_ID (+) AND
      T22.TARGET_PER_ID = T12.CON_ID (+) AND T22.ROW_ID = T12.ACTIVITY_ID (+) AND
      T22.TARGET_PER_ID = T15.ROW_ID (+) AND
      T22.TARGET_PER_ID = T2.PAR_ROW_ID (+) AND
      T22.PR_OPTY_ID = T3.ROW_ID (+) AND
      ((T22.TODO_PLAN_END_DT <= TO_DATE('03/14/2018 12:32:15','MM/DD/YYYY HH24:MI:SS')
      AND T22.TODO_PLAN_START_DT >= TO_DATE('03/13/2018 21:00:00','MM/DD/YYYY HH24:MI:SS') - 90
      AND (NOT (T22.TODO_CD = 'Звонок - исходящий' AND T22.X_SUB_TYPE_CD IS NOT NULL AND ((T22.X_SUB_TYPE_CD = 'День рождения клиента' OR
       T22.X_SUB_TYPE_CD = 'Окончание срока действия-карта' OR T22.X_SUB_TYPE_CD ='Окончание срока действия-вклад')
       OR (T22.X_SUB_TYPE_CD = 'Окончание срока действия-СС' OR T22.X_SUB_TYPE_CD = 'Окончание действия паспорта' OR T22.X_SUB_TYPE_CD = 'Уменьшение активов Клиента') OR
       (T22.X_SUB_TYPE_CD = 'ПУ - баланс меньше порога' OR T22.X_SUB_TYPE_CD = 'ПУ - истек льготный период'
        OR T22.X_SUB_TYPE_CD = 'Увеличение активов Клиента') OR (T22.X_SUB_TYPE_CD = 'Арест'
        OR T22.X_SUB_TYPE_CD = 'Взыскание' OR T22.X_SUB_TYPE_CD = 'Снятие ареста' OR T22.X_SUB_TYPE_CD = 'Актуализация ПДн') OR (T22.X_SUB_TYPE_CD = 'Алерт'
        OR T22.X_SUB_TYPE_CD = 'FATCA' OR T22.X_SUB_TYPE_CD = 'Обучение УКО')))) AND T22.CAL_TYPE_CD ='Активности/Календарь'
        ) AND
      (T22.TEMPLATE_FLG = 'N' AND (T22.TODO_CD ='Встреча' OR T22.TODO_CD = 'Звонок - исходящий') AND T22.EVT_STAT_CD ='Запланирована')) AND
      (T22.OWNER_PER_ID = '%s')
and rownum <= 50
   ORDER BY
      T22.OWNER_PER_ID DESC, T22.TODO_PLAN_START_DT DESC
